### ISSUE TITLE
Should we break this down by saplings vs adults?

### ISSUE THREAD

**Issue by alanaroseo** [lizzieinvancouver/grephon#17] opened 2023-07-16 13:00 UTC
Hey @ALL, From what I can tell, exogenous factors are more likely to be found for adult trees. But some studies are not quite clear if adults or saplings. I can add a column and then you can agree or disagree, but it might be  simpler if you add them yourself if you have not yet sent Lizzie your "authors_looked" updates (Issue #11 )
Yes? No?

**Comment by rdmanzanedo** [comment] 2023-07-17 07:52
That's a really interesting. I actually didn't record this on my mind as I was reading them but I guess it wouldn't be a huge amount of work to add? (do we have an idea of how many many are unclear about this?)

**Comment by lizzieinvancouver** [comment] 2023-07-17 13:27
@alanaroseo Great idea! One hiccup could be studies that include both ... I bet @jannekehrl  has some so will aim to discuss today.

**Comment by lizzieinvancouver** [comment] 2023-07-20 16:07
Okay, discussion of this on Monday suggested it's a good metric, but would be better just to add it in R (versus updating files at all). Here's all the papers:

```
> sort(unique(dall$paper_id))
 [1] "Brand2022"                "bruening2017"             "buermann2018"             "Camarero2022"            
 [5] "Chen1998"                 "Chen2000"                 "cufar2014"                "Cuny2012"                
 [9] "delpierre2017"            "desauvage2022"            "dow2022"                  "Drew & Downes 2018"      
[13] "eckes-shephard2020"       "Etzold2021"               "Finzi2020"                "francon2020"             
[17] "Gao2022"                  "grossiord2022"            "Keenan et al 2014"        "kolar2016"               
[21] "mckown2016"               "michelot2012"             "Moser2019"                "Oddi2022"                
[25] "Ren2019"                  "Richardson2020"           "Sebastian-Azcona2020"     "Silvestro2023"           
[29] "Soolananayakanahally2013" "Soolananayakanahally2014" "Stridbeck2022"            "Vitasse2009"             
[33] "wheeler2016"              "Zani2020"                 "Zhang2021"                "Zhu2021"                 
[37] "Zohner2020"               "Zohnerpreprint"   
```

The following are greenhouse:

> dall$paper_id[grep("greenhouse", dall$study_type)]
[1] "Zani2020"                 "Zohnerpreprint"           "Soolananayakanahally2013" "mckown2016"              
[5] "mckown2016"               "mckown2016"               "grossiord2022"  

@jannekehrl @AileneKane @alanaroseo @cchambe12 -- could you tell me the vague age (seedling/sapling/??) of these? And any other rows that might be juveniles?

@rdmanzanedo @FrederikBaumgarten Any non-adults in your studies?

**Comment by cchambe12** [comment] 2023-07-24 11:59
@lizzieinvancouver For McKown2016, it says individuals were planted as "young trees" in 2008 and then monitored in 2012 - so maybe saplings?

**Comment by alanaroseo** [comment] 2023-07-25 19:28
Soolananayakanahally2013 is saplings or seedlings they are vague about that but I bet small because they did biomass

**Comment by lizzieinvancouver** [comment] 2023-07-26 09:49
grossiord2022 is mine: they planted out 2-year old individuals (in the big outdoor chambers at WSL) in winter 2018 and started the experiment in 2019. 

I feel like we should just have 'adult' and 'juvenile' as categories since most papers seem wishy-washy.

@jannekehrl or @AileneKane Can you update for "Zani2020" "Zohnerpreprint" ? I suspect it may depend on which row, so feel free to specify based on values in some other column. Thanks.

**Comment by lizzieinvancouver** [comment] 2023-07-28 13:36
@kavs-P Hoping you can help with this! Though, please, check I think @alanaroseo may have done some of this already....

**Comment by rdmanzanedo** [comment] 2023-07-28 13:42
@alanaroseo Mine's and Freddi's seem ok except for sebastian-azcona2020, which is classsified as juveniles but, as far as I understand, it's 39 year old picea trees (I guess those are already reproductive and adults despite being rather young). Worth changing?

**Comment by AileneKane** [comment] 2023-08-09 17:14
@alanaroseo sorry for the delay on this! for 1 experiment, they used "5-yr-old individuals of European beech (Fagus
sylvatica) and Japanese meadowsweet (Spiraea japonica)" and experiment 2 was 2-yr-old individuals of silver birch
(Betula pendula).

**Comment by lizzieinvancouver** [comment] 2023-08-27 19:59
Here's the current update:

```
> d[,c("paper_id", "age_class"),]
                   paper_id age_class
1                 brand2022     adult
2              bruening2017      <NA>
3              buermann2018     adult
4              camarero2022     adult
5                  chen1998     adult
6                  chen1998     adult
7                  chen2000      <NA>
8                 cufar2014     adult
9                  cuny2012     adult
10            delpierre2017     adult
11            delpierre2017     adult
12            desauvage2022     adult
13                  dow2022     adult
14                  dow2022     adult
15       drew & downes 2018     adult
16       eckes-shephard2020     adult
17               etzold2021     adult
18               etzold2021     adult
19                finzi2020     adult
20                finzi2020     adult
21              francon2020     adult
22                  gao2022     adult
23                  gao2022     adult
24            grossiord2022  juvenile
25        keenan et al 2014     adult
26                kolar2016     adult
27               mckown2016  juvenile
28               mckown2016  juvenile
29               mckown2016  juvenile
30             michelot2012     adult
31             michelot2012     adult
32                moser2019     adult
33                 oddi2022     adult
34                 oddi2022     adult
35                  ren2019     adult
36           richardson2020      <NA>
37           richardson2020      <NA>
38           richardson2020      <NA>
39     sebastian-azcona2020     adult
40            silvestro2023     adult
41            silvestro2023     adult
42 soolananayakanahally2013  juvenile
43 soolananayakanahally2013  juvenile
44 soolananayakanahally2013  juvenile
45            stridbeck2022     adult
46            stridbeck2022     adult
47              vitasse2009  juvenile
48              wheeler2016     adult
49                 zani2020     adult
50                 zani2020     adult
51                 zani2020  juvenile
52                zhang2021     adult
53                  zhu2021     adult
54                  zhu2021     adult
55               zohner2020      <NA>
56               zohner2023     adult
57               zohner2023     adult
58               zohner2023     adult
59               zohner2023     adult
60               zohner2023  juvenile
```

I closing for now. If we end up needing this more, we can return to it to fix the NA or such. 

Thank you @alanaroseo for all your help!

**Closed as completed** 2023-08-27 19:59 UTC
